#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'storm_types'

        module BackType
          module Storm
            module DistributedRPC
              class Client
                include ::Thrift::Client

                def execute(functionName, funcArgs)
                  send_execute(functionName, funcArgs)
                  return recv_execute()
                end

                def send_execute(functionName, funcArgs)
                  send_message('execute', Execute_args, :functionName => functionName, :funcArgs => funcArgs)
                end

                def recv_execute()
                  result = receive_message(Execute_result)
                  return result.success unless result.success.nil?
                  raise result.e unless result.e.nil?
                  raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'execute failed: unknown result')
                end

              end

              class Processor
                include ::Thrift::Processor

                def process_execute(seqid, iprot, oprot)
                  args = read_args(iprot, Execute_args)
                  result = Execute_result.new()
                  begin
                    result.success = @handler.execute(args.functionName, args.funcArgs)
                  rescue BackType::Storm::DRPCExecutionException => e
                    result.e = e
                  end
                  write_result(result, oprot, 'execute', seqid)
                end

              end

              # HELPER FUNCTIONS AND STRUCTURES

              class Execute_args
                include ::Thrift::Struct, ::Thrift::Struct_Union
                FUNCTIONNAME = 1
                FUNCARGS = 2

                FIELDS = {
                  FUNCTIONNAME => {:type => ::Thrift::Types::STRING, :name => 'functionName'},
                  FUNCARGS => {:type => ::Thrift::Types::STRING, :name => 'funcArgs'}
                }

                def struct_fields; FIELDS; end

                def validate
                end

                ::Thrift::Struct.generate_accessors self
              end

              class Execute_result
                include ::Thrift::Struct, ::Thrift::Struct_Union
                SUCCESS = 0
                E = 1

                FIELDS = {
                  SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'},
                  E => {:type => ::Thrift::Types::STRUCT, :name => 'e', :class => BackType::Storm::DRPCExecutionException}
                }

                def struct_fields; FIELDS; end

                def validate
                end

                ::Thrift::Struct.generate_accessors self
              end

            end

          end
        end
