/*
 * Generated by saveVersion.sh
 */
@VersionAnnotation(version="0.10.0-SNAPSHOT", revision="ffba148cc47a92185fa1a5db11f72982de10f106", branch="storm-243",
                         user="caokun", date="Thu Jan  8 10:47:48 CST 2015", url="https://github.com/caofangkun/apache-storm.git ",
                         srcChecksum="97e7c942939e3e82dcb854b497991a51")
package backtype.storm.utils;
