#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'storm_thrift/thrift/storm_types'

module StormThrift

    module BackType
      module Storm
  end
end

end